#' Y vector for regression
#'
#' This function establishes the Y vector for a specific set of m-values (Equation 11, Anderson et al., 2017).
#' @param datHMF The data matrix with scaled measurements measurements. Scaled center measurements are provided for
#' each measurement/annotation (e.g., gene/organ) combination. This format is produced by scale_zeroOne(). Defaults to datHMF.
#' @param Y The Y data obtained with getXY(). Defaults to NULL.
#' @param numPar The number of parameters found by multiplying the number of annotations
#' by the number of measured features (e.g., number of organs * number of genes).
#' numPar = ((ncol(datHMF)-2)^2)*(length(unique(datHMF[,2]))^2). Defaults to NULL.
#' @param mRange The m-value range. Defaults to NULL.
#' @return The Y vector for regression analysis
#' @export
#' @examples Yreg = get_Yreg(datHMF,XY$Y,numPar,mRange)
#' @references \url{http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005627}
get_Yreg = function(datHMF=NULL,Y=NULL,numPar=NULL,mRange=NULL){
  #Yreg <- matrix( c(0), sqrt(numPar)*length(mRange), 1 )
  genes  = 1:(ncol(datHMF)-2)
  #genes  = c(1,2,4,7,10,13,16,19,22,3,6,9,12,15,18,21,24,11,14,17,20,23)
  organs = 1:length(unique(datHMF[,2]))
  #browser()
  Yreg0  = Y[mRange, genes, organs, drop= F]     
  Yreg = as.matrix(as.vector(Yreg0),1,sparse=T)  # set Y regression matrix
  return(Yreg)
} # end get_Yreg



#' X matrix for regression
#'
#' This function establishes the X matrix for a specific set of m-values (Equation 11, Anderson et al., 2017).
#' @param datHMF The data matrix with scaled measurements measurements. Scaled center measurements are provided for
#' each measurement/annotation (e.g., gene/organ) combination. This format is produced by scale_zeroOne(). Defaults to datHMF.
#' @param X The X data obtained with getXY(). Defaults to NULL.
#' @param numPar The number of parameters found by multiplying the number of annotations
#' by the number of measured features (e.g., number of orggans * number of genes).
#' numPar = ((ncol(datHMF)-2)^2)*(length(unique(datHMF[,2]))^2). Defaults to NULL.
#' @param mRange The m-value range. Defaults to NULL.
#' @return The Y vector for regression analysis
#' @export
#' @examples Xreg = get_Xreg(datHMF,XY$Y,numPar,mRange)
#' @references \url{http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005627}
get_Xreg = function(datHMF=NULL,X=NULL,numPar=NULL,mRange=NULL){
  #Xreg <- matrix( c(0), sqrt(numPar)*length(mRange), numPar  )

  #XX <- matrix(c(0),length(mRange),sqrt(numPar))
  
  genes  = 1:(ncol(datHMF)-2); 
  #genes  = c(1,2,4,7,10,13,16,19,22,3,6,9,12,15,18,21,24,11,14,17,20,23)
  organs = 1:length(unique(datHMF[,2]))
  #browser()
  XX1 = X[mRange,genes,organs,drop=F]
  XX = matrix(XX1, nrow = length(mRange),ncol = sqrt(numPar),byrow = F)
  Xreg = Diagonal(sqrt(numPar)) %x% XX
  return(Xreg)
} # end get_Xreg


#' Get rate constants
#'
#' This function formats the rate constant data after the fir has been implemented using glmnet() from the glmnet library.
#' Sometimes glmnet() produces less fits than requested based on the nlambda parameter. In such cases, get_rateConst()
#' pads the parameter matrix with zeros such that the size of the matrix reflects the selection of nlambda.
#' @param fit The entire fit values from the fit object generated by glmnet().
#' @param nlambda The number of lambda values.
#' @return The rate constant matrix.
#' @examples rateConst = get_rateConst(fit$beta,nlambda)
#' @references \url{https://www.jstatsoft.org/article/view/v033i01}
get_rateConst = function(fit=NULL,nlambda=NULL){
  rateConst <- data.matrix(fit$beta)
  if(ncol(rateConst)<nlambda){
    del = nlambda - ncol(rateConst)
    addcol = matrix(c(0),nrow(rateConst),del)
    rateConst = cbind(rateConst,addcol)
    
    fit$lambda = c(fit$lambda,rep(max(fit$lambda),del))
    fit$beta = rateConst
  }
  return(fit)
} # end get_rateConst
